version: '3.9'

services:
    db:
        image: mysql:8
        restart: unless-stopped
        ports:
            - '3306:3306'
        environment:
            - MYSQL_ROOT_PASSWORD=password
            - MYSQL_USER=mysql-user
            - MYSQL_PASSWORD=mysql
            - MYSQL_DATABASE=workouts
        volumes:
            - './mocks/dbTestData:/docker-entrypoint-initdb.d/:ro'
