version: '3.9'

services:
    db:
        image: postgis/postgis
        restart: unless-stopped
        ports:
            - '5432:5432'
        environment:
            - POSTGRES_USER=mysql-user
            - POSTGRES_PASSWORD=mysql
            - POSTGRES_DB=workouts
        volumes:
            - './mocks/dbTestData:/docker-entrypoint-initdb.d/:ro'
