CREATE EXTENSION postgis;

DROP TABLE IF EXISTS users;

create table
    public.users (
        id bigint generated by default as identity,
        username character varying not null,
        name character varying not null,
        is_demo boolean not null,
        last_login timestamp without time zone null,
        login_count integer not null default 0,
        created_at timestamp without time zone not null,
        updated_at timestamp without time zone not null,
        constraint users_pkey primary key (id),
        constraint users_id_key unique (id),
        constraint users_username_key unique (username)
    ) tablespace pg_default;

DROP TABLE IF EXISTS labels;

create table
    public.labels (
        id bigint generated by default as identity,
        color character varying not null,
        value character varying not null,
        user_id bigint not null,
        created_at timestamp without time zone not null,
        updated_at timestamp without time zone not null,
        constraint labels_pkey primary key (id),
        constraint labels_id_key unique (id),
        constraint labels_user_id_fkey foreign key (user_id) references users (id) on delete cascade
    ) tablespace pg_default;

DROP TABLE IF EXISTS workouts;

create table
    public.workouts (
        id bigint generated by default as identity,
        type character varying not null,
        timestamp timestamp without time zone not null,
        timezone character varying not null,
        date_only boolean not null default false,
        distance double precision not null,
        duration double precision not null,
        pace double precision not null,
        speed double precision not null,
        notes character varying null,
        geometry geometry null,
        user_id bigint not null,
        label_id bigint null,
        created_at timestamp without time zone not null,
        updated_at timestamp without time zone not null,
        constraint workouts_pkey primary key (id),
        constraint workouts_id_key unique (id),
        constraint workouts_label_id_fkey foreign key (label_id) references labels (id),
        constraint workouts_user_id_fkey foreign key (user_id) references users (id) on delete cascade
    ) tablespace pg_default;