export const labelColors = [
    '#b40813',
    '#d6411d',
    '#fac82f',
    '#198921',
    '#0c6b74',
    '#2579d8',
    '#0c56c9',
    '#542be3',
];

export const daysOfWeek = ['Mo', 'Tu', 'We', 'Th', 'Fr', 'Sa', 'Su'];

export const months = [
    { short: 'Jan', long: 'January' },
    { short: 'Feb', long: 'February' },
    { short: 'Mar', long: 'March' },
    { short: 'Apr', long: 'April' },
    { short: 'May', long: 'May' },
    { short: 'Jun', long: 'June' },
    { short: 'Jul', long: 'July' },
    { short: 'Aug', long: 'August' },
    { short: 'Sep', long: 'September' },
    { short: 'Oct', long: 'October' },
    { short: 'Nov', long: 'November' },
    { short: 'Dec', long: 'December' },
];

export enum _t {
    accountCreated = 'Account Created',
    accountDeletion = 'Account Deletion',
    accountSettings = 'Account Settings',
    activity = 'Activity',
    allWorkoutsToggle = 'All Workouts',
    bestResults = 'Best Results',
    btnAddData = 'Add data manually',
    btnAddLabel = '+',
    btnAddWorkout = 'Add Workout',
    btnDone = 'Done',
    btnEditWorkout = 'Edit Workout Data',
    btnCancel = 'Cancel',
    btnClose = 'Close',
    btnDeleteAccount = 'Delete Account',
    btnFileInput = 'Browse',
    btnGetStarted = 'Get Started',
    btnLogin = 'Sign in',
    btnSelectLabel = 'Select Label',
    btnSignup = 'Create Account',
    btnToday = 'Today',
    btnUpload = 'Upload',
    btnUploadFile = 'Upload File',
    chartSectionH = 'Overview',
    copyright = '© 2023 Mariusz Las',
    dataDeletionHeader = 'Workout Deletion',
    dataPreviewHeader = 'Data Preview',
    dataUploadHeader = 'Data Upload',
    durationFormHeader = 'Enter Duration',
    dataToUpload = 'Data to upload',
    date = 'Date',
    dateCreated = 'Member Since',
    delete = 'Delete',
    deleteConfirmation = 'Are you sure you want to delete this workout?',
    demoAccountLimit = 'This is a demo account which has a maximum limit of 1000 workouts',
    distance = 'Distance',
    distanceKm = 'Distance (km)',
    distanceKmShort = 'Dist. (km)',
    duration = 'Duration',
    edit = 'Edit',
    editConfirmation = 'Are you sure you want to replace the workout?',
    emailConfirmationHeader = 'Email Confirmation',
    emailConfirmationBody1 = 'We have sent a verification link to ',
    emailConfirmationBody2 = '. Please check your inbox and click the link to verify your account.',
    errorDataInput = 'Incorrect data input',
    errorDataUpload = 'Error uploading data!',
    errorDeleteWorkout = 'Could not delete the workout',
    errorDemoFileSize = 'Maximum file size for demo users is 1 MB',
    errorFetch = 'Something went wrong on our side. We could not fetch the workout data',
    errorFetchBestResults = 'Could not fetch best results',
    errorFetchLabels = 'Failed to fetch the labels',
    errorFetchUserData = 'Could not fetch user details',
    errorFetchWorkout = 'Could not fetch workout data',
    errorFetchWorkoutTrajectory = 'Could not fetch workout trajectory',
    errorGeneric = 'Error!',
    errorIntTime = 'The time component must be an integer',
    errorInvActivType = 'Invalid activity type',
    errorMinDistance = 'Minimum distance is 0.5 km',
    errorNegativeTime = 'The time component cannot be less than 0',
    errorPreview = 'Could Not Generate Data Preview',
    errorLabelDuplicate = 'This label already exists',
    errorLabelInputBadChar = 'Input must not contain the following characters: ";"',
    errorLabelInputLength = 'A label must contain between 1 and 25 characters',
    errorNewUsers = 'New users are not currently accepted',
    errorPageNotFoundTitle = 'Page Not Found',
    errorPageNotFound = "Sorry, we couldn't find the page you're looking for.",
    errorParsingFile = 'Could not parse the file',
    errorPassword1 = 'Passwords do not match!',
    errorPassword2 = 'Password must not be shorter than 8 characters!',
    errorPassword3 = 'Password cannot be "Password"',
    errorPassword4 = 'Password cannot be "password"',
    errorPassword5 = 'Password must contain at least one uppercase letter!',
    errorPassword6 = 'Password must contain at least one number!',
    errorWorkoutDeletion = 'Could not delete the workout',
    fileUploadInfo = 'Only tsx files exported from the Coros Pace app are currently supported',
    filter = 'Filter',
    footer = 'Created by Mariusz Las',
    forgotPass = 'Forgot Password?',
    foundData = 'Found Data',
    h = 'h',
    labelHours = 'Hours',
    labelEmail = 'Email',
    labelMinutes = 'Minutes',
    labelName = 'Name',
    labelPass = 'Password',
    labelPassRep = 'Repeat Password',
    labelNewPass = 'New Password',
    labelNewPassRep = 'Repeat New Password',
    labelPasswordResetCode = 'Password Reset Code',
    labelSeconds = 'Seconds',
    labelTimezone = 'Timezone',
    labelTotalNoWorkout = 'Total Number of Workouts',
    landingHeader = 'Workout Odyssey - where all your fintess data is stored!',
    landingSeoDescription = 'Track your running, walking, and cycling workouts with ease! Workout Odyssey lets you log workouts, upload .tcx files including location data, view workout stats, and see your progress over time. Sign up and start your fitness journey today!',
    landing1Desc = 'Track your workouts and view the graphical summary',
    landing2Desc = 'Monitor various statistics on monthly or year basis or view all of them',
    landing3Desc = 'Get more insight about your workouts in a detailed view',
    landing4Desc = 'View the your best workouts',
    landing1Title = 'Visualize',
    landing2Title = 'Statistics',
    landing3Title = 'View All',
    landing4Title = 'Best Results',
    lastLogin = 'Last Login',
    loginFailed = 'Login failed!',
    loginHeader = 'Sign In',
    loginOffer = 'Already have an account? ',
    loginSubH = 'Enter your account details',
    logo1 = 'Workout',
    logo2 = 'Odyssey',
    km = 'km',
    kmPerHour = 'km/h',
    m = 'min',
    mainMenu = 'Main Menu',
    monthListHeader = 'Workouts this month',
    monthListHeader2 = 'Workouts in ',
    noData = 'No data',
    noFile = 'No file selected',
    noLabels = 'No labels',
    notes = 'Notes',
    noWorkoutsMsg = 'No workouts',
    pace = 'Pace',
    pageTitle = 'Workout Odyssey',
    passwordResetHeader = 'Password Reset',
    passwordResetBody1 = 'Enter your email below. If it matches our records, we will send you a password reset code',
    passwordResetBody2 = 'Enter the password reset code we sent to your email along with a new password',
    passwordResetBtn = 'Reset Password',
    passwordResetRequestBtn = 'Request Reset Password Code',
    passwordResetNoCode = "Didn't get the password reset code?",
    perKm = '/km',
    plcdAddLabel = 'Add a new label',
    plcdHours = 'HH',
    plcdEmail = 'name@example.com',
    plcdMinutes = 'MM',
    plcdName = 'Jon Snow',
    plcdPassword = '********',
    plcdSeconds = 'SS',
    previewMsgAre = 'There are',
    previewMsgIs = 'There is',
    previewMsgFor = 'for',
    previewMsgOn = 'on',
    previewMsgRecord = 'record',
    previewMsgRecordPlural = 'records',
    resendCodeCTA = 'Resend email',
    s = 's',
    selectActivity = 'Workout Type',
    selectDateTime = 'Date and time',
    signupSubH = 'Create your account',
    signupHeader = 'Sign Up',
    signupFailed = 'Registration failed!',
    signupOffer = "Don't have an account? ",
    signOut = 'Sign out',
    sortOptDateDesc = 'Date - earliest first',
    sortOptDateAsc = 'Date - oldest first',
    sortOptDistanceDesc = 'Distance - longest first',
    sortOptDistanceAsc = 'Distance - shortest first',
    sortOptDurationDesc = 'Duration - longest first',
    sortOptDurationAsc = 'Duration - shortest first',
    sortOptPaceDesc = 'Pace - slowest first',
    sortOptPaceAsc = 'Pace - fastest first',
    speed = 'Average speed',
    successDataUpload = 'Data was successfully uploaded!',
    successWorkoutDeletion = 'Workout was successfully deleted',
    successWorkoutEdit = 'Workout was successfully saved',
    toggleDarkMode = 'Toggle Dark Mode',
    toggleLightMode = 'Toggle Light Mode',
    total = 'Total',
    time = 'Time',
    tryAgain = 'Try again',
    unexpectedError = 'Unexpected error ocurred.',
    uploadConfirmation = 'Are you sure you want to upload the workout data?',
    workoutDetails = 'Workout Details',
    workoutProperties = 'Properties',
    year = 'Year',
    yearListHeader = 'All training records',
}
